version: "2"

configs:
  init_script:
    file: /path/to/your/init/script

volumes:
  home:
  workspace:

services:
  zeroclaw:
    image: ilteoood/zeroclaw
    container_name: zeroclaw
    volumes:
      - home:/root
      - workspace:/home/workspace
    configs:
      - source: init_script
        target: /usr/local/bin/init
        mode: 0755
    ports:
      - "42617:42617"
    restart: unless-stopped
