version: "2"

configs:
  init_script:
    file: /path/to/your/init/script

volumes:
  zeroclaw-data:
  workspace:

services:
  dockerclaw:
    image: ilteoood/dockerclaw
    container_name: dockerclaw
    volumes:
      - zeroclaw-data:/zeroclaw-data
      - workspace:/home/workspace
    configs:
      - source: init_script
        target: /usr/local/bin/init
        mode: 0755
    ports:
      - "42617:42617"
    restart: unless-stopped
