FROM ubuntu:25.10

ENV PICOCLAW_MODE=gateway

ARG TARGETARCH

COPY picoclaw/* /usr/local/bin/

RUN chmod +x /usr/local/bin/download_picoclaw /usr/local/bin/entrypoint /usr/local/bin/init && \
    apt-get update && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y --no-install-recommends \
    curl ca-certificates tar && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    download_picoclaw $TARGETARCH && \
    picoclaw onboard

WORKDIR /home/workspace

EXPOSE 18790

ENTRYPOINT [ "entrypoint" ]