FROM ubuntu:25.10

ENV NULLCLAW_MODE=gateway

ARG TARGETARCH

RUN apt-get update && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y --no-install-recommends \
    curl ca-certificates && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY nullclaw/* /usr/local/bin/

RUN chmod +x /usr/local/bin/download_nullclaw /usr/local/bin/entrypoint /usr/local/bin/init && \
    download_nullclaw $TARGETARCH

WORKDIR /home/workspace

EXPOSE 3000

ENTRYPOINT [ "entrypoint" ]