name: Build only image
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build only image job
        permissions:
            contents: read
        steps:
            - name: Checkout master
              uses: actions/checkout@master
            - name: Build image
              uses: ilteoood/docker_buildx@master
              with:
                tag: latest
                platform: linux/arm64
                imageName: ilteoood/dockerclaw
