name: OpenClaw

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          tag: latest
          platform: linux/amd64,linux/arm64
          imageName: ilteoood/openclaw
          dockerFile: Dockerfile.openclaw
          publish: true
          dockerUser: ilteoood
          dockerPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}
